name: Update News Data

on:
  push:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Run Update Script
        env:
          URL_API: ${{ secrets.URL_API }}
          URL_WEBHOOK: ${{ secrets.URL_WEBHOOK }}
        run: node index.js

      - name: Update last-news.json on GitHub
        uses: test-room-7/action-update-file@v1
        with:
          file-path: last-news.json
          commit-msg: Update last-news.json
          github-token: ${{ secrets.GH_TOKEN }}
          branch: main
